- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: stop current running container
      command: docker stop app
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm app
      ignore_errors: yes

    - name: remove app_image
      command: docker rmi app_image
      ignore_errors: yes

    - name: build docker image using the Dockerfile
      command: docker build -t app_image .

    - name: run container
      command: docker run -d --name app -p 5000:8080 app_image
